trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo BuildJob, Step1!
- stage: DevDeploy
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo DevDeploy, Step1!
- stage: QADeploy
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo QADeploy, Step1!
- stage: ProdDeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo ProdDeploy, Step1!
